[package]
name = "codex-git-tooling"
version.workspace = true
edition.workspace = true
readme = "README.md"

[lib]
name = "codex_git_tooling"
path = "src/lib.rs"

[dependencies]
tempfile = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
ts-rs = { workspace = true, features = [
    "uuid-impl",
    "serde-json-impl",
    "no-serde-warnings",
] }

[lints]
workspace = true

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }
