name: 自動同步 Fork
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: openai
          base: main     # 您的分支名稱，根據需要修改
          head: main     # 上游分支名稱，根據需要修改
